### ISSUE TITLE
Add cutout for Astroneer logo

### ISSUE THREAD

**Issue by frozenpandaman** [ricsam/rplaceswe#1]
This is currently what they're building, with permission: https://cdn.discordapp.com/attachments/298254740880490496/298258206285889537/size.png

Would make a PR but not sure what needs to be changed besides swe2.gif (och min svenska är inte så bra…)

**Comment by ricsam** [comment]
Hi! thanks for noticing me, i've added the astronaut as agreed uppon on reddit :) have a nice evning, most swedes are asleep now so requests in /r/swedenonplace might be slow

**Comment by frozenpandaman** [comment]
Thanks!
